---
title: "Severe Weather Event Damage and Fatalities 1950-2011"
author: "Joseph B. Slone"
date: "October 23, 2015"
output: html_document
---

# Initial Setup

This preliminary code loads the required libraries and initializes some constants It then downloads and unzips the source data file.



```{r initial_code, warning=FALSE, message=FALSE, echo=TRUE}
library(R.utils)        # for bunzip2
library(data.table)
library(dplyr)
library(tidyr)
library(RColorBrewer)
library(ggplot2)
library(xtable)

# The URL of the source data file.

data.file.URL <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
target.file <- "StormData.csv.bz2"

# From the Storm Event Table on pg 6 NWSI 10-1605 AUGUST 17, 2007

weather_event_labels <- toupper(c("Astronomical Low Tide",  "Avalanche",
                          "Blizzard", "Coastal Flood",
                          "Cold/Wind Chill", "Debris Flow",
                          "Dense Fog", "Dense Smoke",
                          "Drought", "Dust Devil",
                          "Dust Storm", "Excessive Heat",
                          "Extreme Cold/Wind Chill", "Flash Flood",
                          "Flood", "Frost/Freeze",
                          "Funnel Cloud", "Freezing Fog",
                          "Hail", "Heat",
                          "Heavy Rain", "Heavy Snow",
                          "High Surf", "High Wind",
                          "Hurricane (Typhoon)", "Ice Storm",
                          "Lake-Effect Snow", "Lakeshore Flood",
                          "Lightning", "Marine Hail",
                          "Marine High Wind", "Marine Strong Wind",
                          "Marine Thunderstorm Wind", "Rip Current",
                          "Seiche", "Sleet",
                          "Storm Surge/Tide", "Strong Wind",
                          "Thunderstorm Wind", "Tornado",
                          "Tropical Depression", "Tropical Storm",
                          "Tsunami", "Volcanic Ash",
                          "Waterspout", "Wildfire",
                          "Winter Storm", "Winter Weather"))


#download.file(data.file.URL, target.file)
#bunzip2(target.file)
#StormData <- data.table(read.csv("StormData.csv"))

# Collapse all of the different Hurricanes names into a list so that
# we can have a generic "Hurricane Category

#StormData %>% filter(grepl("Hurricane|HURRICANE",EVTYPE)) -> HurricaneData
#Hurricanes <- unique(as.character(HurricaneData$EVTYPE))


```



## Process the data

```{r process_data }
# Clean the data.  Converting the older event types into the modern
# event types where it is reasonable to do so.

StormData %>%
    mutate(EVTYPE = as.character(EVTYPE)) %>%
    mutate(Event.Type = ifelse(EVTYPE %in% weather_event_labels, EVTYPE, "OTHER")) %>%
    mutate(Event.Type = ifelse(EVTYPE %in% Hurricanes, "HURRICANE", Event.Type )) %>%
    mutate(Event.Type = ifelse(EVTYPE == "TSTM WIND", "THUNDERSTORM WIND", Event.Type)) %>%
    mutate(Event.Type = ifelse(EVTYPE == "THUNDERSTORM WINDS", "THUNDERSTORM WIND", Event.Type)) %>%
    mutate(Event.Type = ifelse(EVTYPE == "HIGH WINDS", "HIGH WIND", Event.Type)) %>%
    mutate(Event.Type = ifelse(EVTYPE == "WILD/FOREST FIRE", "WILDFIRE", Event.Type)) %>%
    mutate(Event.Type = ifelse(EVTYPE == "FLASH FLOODING", "FLASH FLOOD", Event.Type)) %>%
    mutate(Event.Type = ifelse(EVTYPE == "URBAN/SML STREAM FLD", "FLOOD", Event.Type)) %>%
    mutate(Event.Type = ifelse(EVTYPE == "EXTREME COLD", "EXTREME COLD/WIND CHILL", Event.Type)) %>%
    mutate(Event.Type = ifelse(EVTYPE == "FLOODING", "FLOOD", Event.Type)) %>%
    mutate(Event.Type = ifelse(EVTYPE == "RIP CURRENTS", "RIP CURRENT", Event.Type)) %>%
    mutate(Event.Type = ifelse(EVTYPE == "HEAT WAVE", "EXCESSIVE HEAT", Event.Type)) %>%
    mutate(Event.Type = ifelse(EVTYPE == "EXTREME HEAT", "EXCESSIVE HEAT", Event.Type)) %>%
    mutate(Event.Type = ifelse(Event.Type == "OTHER", paste("OTHER-", EVTYPE), Event.Type)) %>%
    select(Event.Type, Property.Damage = PROPDMG , Crop.Damage = CROPDMG, Fatalities = FATALITIES , Injuries = INJURIES) -> StormData.Cleaned

# Summarise the 4 different damage types.

StormData.Cleaned %>%
    select(Event.Type, Property.Damage) %>%
    group_by(Event.Type) %>%
    summarise_each(funs(sum)) %>%
    arrange(desc(Property.Damage)) -> Property.Summary

StormData.Cleaned %>%
    select(Event.Type, Crop.Damage) %>%
    group_by(Event.Type) %>%
    summarise_each(funs(sum)) %>%
    arrange(desc(Crop.Damage)) -> Crops.Summary

StormData.Cleaned %>%
    select(Event.Type, Fatalities) %>%
    group_by(Event.Type) %>%
    summarise_each(funs(sum)) %>%
    arrange(desc(Fatalities)) -> Fatalities.Summary

StormData.Cleaned %>%
    select(Event.Type, Injuries) %>%
    group_by(Event.Type) %>%
    summarise_each(funs(sum)) %>%
    arrange(desc(Injuries)) -> Injuries.Summary

```
## Crop Damage

Cost is in dollars, not adjusted for inflation.

```{r CropDamage, results="asis"}

xt <- xtable(head(Property.Summary, 15))

print(xt, floating=FALSE, type="html", include.rownames=FALSE)
```

## Property Damage

Cost is in dollars, not adjusted for inflation.

```{r PropertyDamage, results="asis"}

xt <- xtable(head(Crops.Summary, 15))

print(xt, floating=FALSE, type="html", include.rownames=FALSE)
```

## Injuries

```{r Injuries, results="asis"}

xt <- xtable(head(Injuries.Summary, 15))
print(xt, floating=FALSE, type="html", include.rownames = FALSE)
```

## Fatalities
```{r Fatalities, results="asis", fig.align='left'}

xt <- xtable(head(Fatalities.Summary, 15))
print(xt, floating=FALSE, type="html", include.rownames=FALSE)


```

```{r Fatalities.plot, fig.align='left', fig.width=10}
ggplot(head(Fatalities.Summary, 15), aes(x=Event.Type, y = Fatalities, fill=Event.Type)) + 
    geom_bar(stat="identity", width=.75, position=position_dodge(width=.8)) +
    xlab("Event Type") + ylab("Fatalities") +
    ggtitle("Top 15 Fatalities") +
    theme(axis.text.x = element_blank())
```
